### ISSUE TITLE
undefined method `fixed_offset_time_zone'

### ISSUE THREAD

**Issue by the-invisible-man** [killbill/killbill-stripe-plugin#10]
Hi, I'm having some issues trying to add a payment method to an existing account using the stripe plugin. I thought for a second it might be that my request wasn't formatted correctly but then I tried with the sample on the readme page and I received the same error. I've tried installing the plugin manually and through kpm but still not luck. Any help would be much appreciated 💯 

I'm attaching the logs:

016-10-13T16:15:17,418+0000 lvl='INFO', log='AbstractValidatingSessionManager', th='http-bio-8080-exec-1', xff='', rId='', aRId='', tRId='', Enabling session validation scheduler...
2016-10-13T16:15:17,507+0000 lvl='INFO', log='EhCacheManager', th='http-bio-8080-exec-1', xff='', rId='', aRId='', tRId='', Using existing EHCache named [shiro-activeSessionCache]
2016-10-13T16:15:17,879+0000 lvl='INFO', log='LoggingFilter', th='http-bio-8080-exec-1', xff='', rId='3fe8aee5-ebb6-42bd-a8a4-6dd00da03506', aRId='', tRId='1', 1 * Server in-bound request
1 > POST http://127.0.0.1:8080/1.0/kb/accounts/72afb3b5-3db1-4fa8-ba62-576f0b3a5b24/paymentMethods
1 > host: 127.0.0.1:8080
1 > authorization: Basic YWRtaW46cGFzc3dvcmQ=
1 > content-type: application/json; charset=utf-8
1 > accept: application/json, text/html
1 > x-killbill-createdby: System
1 > user-agent: Killbill/1.0.0; PHP 7.0.8-2+deb.sury.org~xenial+1 [Linux]
1 > x-killbill-apikey: bob
1 > x-killbill-apisecret: lazar
1 > content-length: 246
1 > 

2016-10-13T16:15:18,718+0000 lvl='WARN', log='KillbillLogWriter', th='Thread-11', xff='', rId='3fe8aee5-ebb6-42bd-a8a4-6dd00da03506', aRId='1', tRId='1', [org.killbill.killbill.osgi.libs.killbill.OSGIKillbillServiceReference@7a132d8][stripe-plugin] Failure in add_payment_method: undefined method `fixed_offset_time_zone' for #<Java::OrgKillbillBillingAccountApi::DefaultAccount:0x5ebbe441>
/var/tmp/bundles/plugins/ruby/killbill-stripe/4.0.0/ROOT/gems/gems/killbill-8.0.0/lib/killbill/gen/api/account.rb:165:in `to_ruby'
/var/tmp/bundles/plugins/ruby/killbill-stripe/4.0.0/ROOT/gems/gems/killbill-8.0.0/lib/killbill/gen/api/account_user_api.rb:100:in `get_account_by_id'
/var/tmp/bundles/plugins/ruby/killbill-stripe/4.0.0/ROOT/lib/stripe/api.rb:102:in `add_payment_method'
/var/tmp/bundles/plugins/ruby/killbill-stripe/4.0.0/ROOT/gems/gems/killbill-8.0.0/lib/killbill/gen/plugin-api/payment_plugin_api.rb:443:in `addPaymentMethod'
Killbill$$Plugin$$Api$$PaymentPluginApi_158241380.gen:13:in `addPaymentMethod'
2016-10-13T16:15:18,792+0000 lvl='WARN', log='LoggingResponse', th='http-bio-8080-exec-1', xff='', rId='3fe8aee5-ebb6-42bd-a8a4-6dd00da03506', aRId='1', tRId='1', Bad request
org.killbill.billing.payment.api.PaymentApiException: Failed to add payment method for account 72afb3b5-3db1-4fa8-ba62-576f0b3a5b24 : undefined method `fixed_offset_time_zone' for #<Java::OrgKillbillBillingAccountApi::DefaultAccount:0x5ebbe441>
	at org.killbill.billing.payment.core.PaymentMethodProcessor$1.doOperation(PaymentMethodProcessor.java:142)
	at org.killbill.billing.payment.core.PaymentMethodProcessor$1.doOperation(PaymentMethodProcessor.java:115)
	at org.killbill.billing.payment.core.ProcessorBase$WithAccountLock.processAccountWithLock(ProcessorBase.java:199)
	at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:182)
	at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:163)
	at org.killbill.billing.payment.dispatcher.CallableWithRequestData.call(CallableWithRequestData.java:63)
	at org.killbill.commons.concurrent.WrappedCallable.call(WrappedCallable.java:42)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-10-13T16:15:18,799+0000 lvl='INFO', log='LoggingFilter', th='http-bio-8080-exec-1', xff='', rId='3fe8aee5-ebb6-42bd-a8a4-6dd00da03506', aRId='1', tRId='1', 1 * Server out-bound response
1 < 400
1 < Content-Type: application/json
1 <

**Comment by the-invisible-man** [comment]
Just ended up using docker.
