### ISSUE TITLE
Error adding payment method

### ISSUE THREAD

**Issue by husam-otri** [killbill/killbill-stripe-plugin#7]
Hi Guys; i have got this error; when try to add a credit card; 
i'm using killbill 0.14.0
stripe : 1.0.0
 any help to fix this issue? 
Thanks

Killbill$$Plugin$$Api$$PaymentPluginApi_333871130.gen:13:in `addPaymentMethod'
2015-06-17 06:35:41,340 [Plugin-th-105] WARN  o.k.b.p.core.PaymentMethodProcessor - Error adding payment method a84bb605-8bdb-4821-83a9-04d1bd0ca590 for plugin killbill-stripe
org.killbill.billing.payment.plugin.api.PaymentPluginApiException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.jruby.javasupport.JavaConstructor.newInstanceDirect(JavaConstructor.java:284)
	at org.jruby.java.invokers.ConstructorInvoker.call(ConstructorInvoker.java:97)
	at org.jruby.java.invokers.ConstructorInvoker.call(ConstructorInvoker.java:193)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:356)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:213)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:217)
	at org.jruby.java.proxies.ConcreteJavaProxy$InitializeMethod.call(ConcreteJavaProxy.java:60)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:211)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:217)
	at org.jruby.RubyClass.newInstance(RubyClass.java:863)
	at org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrTwoOrNBlock.call(JavaMethod.java:318)
	at org.jruby.java.proxies.ConcreteJavaProxy$NewMethod.call(ConcreteJavaProxy.java:162)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)
	at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
	at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.RescueBodyNode.interpret(RescueBodyNode.java:108)
	at org.jruby.ast.RescueNode.handleException(RescueNode.java:174)
	at org.jruby.ast.RescueNode.interpret(RescueNode.java:120)
	at org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
	at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:112)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:169)
	at Killbill$$Plugin$$Api$$PaymentPluginApi_333871130.addPaymentMethod(Killbill$$Plugin$$Api$$PaymentPluginApi_333871130.gen:13)
	at org.killbill.billing.osgi.bundles.jruby.JRubyPaymentPlugin$9.doCall(JRubyPaymentPlugin.java:159)
	at org.killbill.billing.osgi.bundles.jruby.JRubyPaymentPlugin$9.doCall(JRubyPaymentPlugin.java:156)
	at org.killbill.billing.osgi.bundles.jruby.JRubyPlugin.callWithRuntimeAndChecking(JRubyPlugin.java:276)
	at org.killbill.billing.osgi.bundles.jruby.JRubyPaymentPlugin.addPaymentMethod(JRubyPaymentPlugin.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.killbill.billing.osgi.ContextClassLoaderHelper$1$1.execute(ContextClassLoaderHelper.java:83)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:37)
	at org.killbill.billing.osgi.ContextClassLoaderHelper$1.invoke(ContextClassLoaderHelper.java:80)
	at com.sun.proxy.$Proxy133.addPaymentMethod(Unknown Source)
	at org.killbill.billing.payment.core.PaymentMethodProcessor$1.doOperation(PaymentMethodProcessor.java:116)
	at org.killbill.billing.payment.core.PaymentMethodProcessor$1.doOperation(PaymentMethodProcessor.java:107)
	at org.killbill.billing.payment.core.ProcessorBase$WithAccountLock.processAccountWithLock(ProcessorBase.java:219)
	at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:208)
	at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:192)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-06-17 06:35:41,341 [http-bio-8080-exec-6] WARN  o.k.b.j.mappers.ExceptionMapperBase - Bad request
org.killbill.billing.payment.api.PaymentApiException: Failed to add payment method for account 7df5b5fd-8d1f-412d-83ff-ca9db3181d10 : undefined method `[]' for nil:NilClass
	at org.killbill.billing.payment.core.PaymentMethodProcessor$1.doOperation(PaymentMethodProcessor.java:126)
	at org.killbill.billing.payment.core.PaymentMethodProcessor$1.doOperation(PaymentMethodProcessor.java:107)
	at org.killbill.billing.payment.core.ProcessorBase$WithAccountLock.processAccountWithLock(ProcessorBase.java:219)
	at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:208)
	at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:192)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
org.killbill.billing.payment.api.PaymentApiException: Failed to add payment method for account 7df5b5fd-8d1f-412d-83ff-ca9db3181d10 : undefined method `[]' for nil:NilClass

**Comment by pierre** [comment]
This looks like a configuration issue.

Did you configure your credentials for your tenant according to the [README](https://github.com/killbill/killbill-stripe-plugin/blob/master/README.md)?

**Comment by husam-otri** [comment]
Actually i followed up this tutorial http://docs.killbill.io/0.14/multi_gateways.html

and everything is working fine locally; but i have got this issue on the staging server! 
however; i run this configuration now 
curl -v \
     -X POST \
     -u admin:password \
     -H 'X-Killbill-ApiKey: bob' \
     -H 'X-Killbill-ApiSecret: lazar' \
     -H 'X-Killbill-CreatedBy: admin' \
     -H 'Content-Type: text/plain' \
     -d ':stripe:
  :api_secret_key: "your-secret-key"
  :api_publishable_key: "your-publishable-key"' \
     http://127.0.0.1:8080/1.0/kb/tenants/uploadPluginConfig/killbill-stripe

but i have got the same error again!

**Comment by pierre** [comment]
Can you share the full logs from the server, as well as the HTTP requests you are making?

**Comment by husam-otri** [comment]
Yea; sure; this the full HTTP request;
thanks


2015-06-17 11:30:30,125 [http-bio-8080-exec-3] INFO  c.s.j.a.c.filter.LoggingFilter - 51 * Server in-bound request
51 > POST http://130.211.148.11:8080/1.0/kb/accounts/7df5b5fd-8d1f-412d-83ff-ca9db3181d10/paymentMethods?isDefault=true
51 > host: 130.211.148.11:8080
51 > x-killbill-apikey: bob
51 > accept: application/json
51 > x-killbill-apisecret: lazar
51 > x-killbill-createdby: 1
51 > content-type: application/json
51 > authorization: Basic YWRtaW46cGFzc3dvcmQ=
51 > connection: keep-alive
51 > user-agent: NING/1.0
51 > content-length: 117
51 > 

2015-06-17 11:30:30,171 [Thread-4] WARN  o.k.b.k.0.2.0 - [stripe-plugin] Failure in add_payment_method: undefined method `[]' for nil:NilClass
/var/tmp/bundles/plugins/ruby/killbill-stripe/1.0.0/ROOT/lib/stripe/api.rb:7:in `initialize'
org/jruby/RubyProc.java:271:in `call'
/var/tmp/bundles/plugins/ruby/killbill-stripe/1.0.0/ROOT/gems/gems/killbill-4.0.0/lib/killbill/helpers/active_merchant/gateway.rb:8:in `wrap'
/var/tmp/bundles/plugins/ruby/killbill-stripe/1.0.0/ROOT/gems/gems/killbill-4.0.0/lib/killbill/helpers/active_merchant/configuration.rb:87:in `extract_gateway_config'
/var/tmp/bundles/plugins/ruby/killbill-stripe/1.0.0/ROOT/gems/gems/killbill-4.0.0/lib/killbill/helpers/active_merchant/configuration.rb:38:in `gateways'
/var/tmp/bundles/plugins/ruby/killbill-stripe/1.0.0/ROOT/gems/gems/killbill-4.0.0/lib/killbill/helpers/active_merchant/payment_plugin.rb:590:in `lookup_gateway'
/var/tmp/bundles/plugins/ruby/killbill-stripe/1.0.0/ROOT/gems/gems/killbill-4.0.0/lib/killbill/helpers/active_merchant/payment_plugin.rb:170:in `add_payment_method'
/var/tmp/bundles/plugins/ruby/killbill-stripe/1.0.0/ROOT/lib/stripe/api.rb:111:in `add_payment_method'
/var/tmp/bundles/plugins/ruby/killbill-stripe/1.0.0/ROOT/gems/gems/killbill-4.0.0/lib/killbill/gen/plugin-api/payment_plugin_api.rb:443:in `addPaymentMethod'
Killbill$$Plugin$$Api$$PaymentPluginApi_327032570.gen:13:in `addPaymentMethod'
2015-06-17 11:30:30,172 [Thread-4] WARN  o.k.b.k.0.2.0 - [stripe-plugin] Failure in add_payment_method: undefined method `[]' for nil:NilClass
/var/tmp/bundles/plugins/ruby/killbill-stripe/1.0.0/ROOT/lib/stripe/api.rb:7:in `initialize'
org/jruby/RubyProc.java:271:in `call'
/var/tmp/bundles/plugins/ruby/killbill-stripe/1.0.0/ROOT/gems/gems/killbill-4.0.0/lib/killbill/helpers/active_merchant/gateway.rb:8:in `wrap'
/var/tmp/bundles/plugins/ruby/killbill-stripe/1.0.0/ROOT/gems/gems/killbill-4.0.0/lib/killbill/helpers/active_merchant/configuration.rb:87:in `extract_gateway_config'
/var/tmp/bundles/plugins/ruby/killbill-stripe/1.0.0/ROOT/gems/gems/killbill-4.0.0/lib/killbill/helpers/active_merchant/configuration.rb:38:in `gateways'
/var/tmp/bundles/plugins/ruby/killbill-stripe/1.0.0/ROOT/gems/gems/killbill-4.0.0/lib/killbill/helpers/active_merchant/payment_plugin.rb:590:in `lookup_gateway'
/var/tmp/bundles/plugins/ruby/killbill-stripe/1.0.0/ROOT/gems/gems/killbill-4.0.0/lib/killbill/helpers/active_merchant/payment_plugin.rb:170:in `add_payment_method'
/var/tmp/bundles/plugins/ruby/killbill-stripe/1.0.0/ROOT/lib/stripe/api.rb:111:in `add_payment_method'
/var/tmp/bundles/plugins/ruby/killbill-stripe/1.0.0/ROOT/gems/gems/killbill-4.0.0/lib/killbill/gen/plugin-api/payment_plugin_api.rb:443:in `addPaymentMethod'
Killbill$$Plugin$$Api$$PaymentPluginApi_327032570.gen:13:in `addPaymentMethod'
2015-06-17 11:30:30,174 [Plugin-th-145] WARN  o.k.b.p.core.PaymentMethodProcessor - Error adding payment method d35355ae-0724-449a-a404-011115fa7fd3 for plugin killbill-stripe
org.killbill.billing.payment.plugin.api.PaymentPluginApiException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.jruby.javasupport.JavaConstructor.newInstanceDirect(JavaConstructor.java:284)
	at org.jruby.java.invokers.ConstructorInvoker.call(ConstructorInvoker.java:97)
	at org.jruby.java.invokers.ConstructorInvoker.call(ConstructorInvoker.java:193)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:356)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:213)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:217)
	at org.jruby.java.proxies.ConcreteJavaProxy$InitializeMethod.call(ConcreteJavaProxy.java:60)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:356)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:213)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:217)
	at org.jruby.RubyClass.newInstance(RubyClass.java:863)
	at org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrTwoOrNBlock.call(JavaMethod.java:318)
	at org.jruby.java.proxies.ConcreteJavaProxy$NewMethod.call(ConcreteJavaProxy.java:162)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
	at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
	at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.RescueBodyNode.interpret(RescueBodyNode.java:108)
	at org.jruby.ast.RescueNode.handleException(RescueNode.java:174)
	at org.jruby.ast.RescueNode.interpret(RescueNode.java:120)
	at org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
	at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:112)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:169)
	at Killbill$$Plugin$$Api$$PaymentPluginApi_327032570.addPaymentMethod(Killbill$$Plugin$$Api$$PaymentPluginApi_327032570.gen:13)
	at org.killbill.billing.osgi.bundles.jruby.JRubyPaymentPlugin$9.doCall(JRubyPaymentPlugin.java:159)
	at org.killbill.billing.osgi.bundles.jruby.JRubyPaymentPlugin$9.doCall(JRubyPaymentPlugin.java:156)
	at org.killbill.billing.osgi.bundles.jruby.JRubyPlugin.callWithRuntimeAndChecking(JRubyPlugin.java:276)
	at org.killbill.billing.osgi.bundles.jruby.JRubyPaymentPlugin.addPaymentMethod(JRubyPaymentPlugin.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.killbill.billing.osgi.ContextClassLoaderHelper$1$1.execute(ContextClassLoaderHelper.java:83)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:37)
	at org.killbill.billing.osgi.ContextClassLoaderHelper$1.invoke(ContextClassLoaderHelper.java:80)
	at com.sun.proxy.$Proxy133.addPaymentMethod(Unknown Source)
	at org.killbill.billing.payment.core.PaymentMethodProcessor$1.doOperation(PaymentMethodProcessor.java:116)
	at org.killbill.billing.payment.core.PaymentMethodProcessor$1.doOperation(PaymentMethodProcessor.java:107)
	at org.killbill.billing.payment.core.ProcessorBase$WithAccountLock.processAccountWithLock(ProcessorBase.java:219)
	at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:208)
	at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:192)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-06-17 11:30:30,176 [http-bio-8080-exec-3] WARN  o.k.b.j.mappers.ExceptionMapperBase - Bad request
org.killbill.billing.payment.api.PaymentApiException: Failed to add payment method for account 7df5b5fd-8d1f-412d-83ff-ca9db3181d10 : undefined method `[]' for nil:NilClass
	at org.killbill.billing.payment.core.PaymentMethodProcessor$1.doOperation(PaymentMethodProcessor.java:126)
	at org.killbill.billing.payment.core.PaymentMethodProcessor$1.doOperation(PaymentMethodProcessor.java:107)
	at org.killbill.billing.payment.core.ProcessorBase$WithAccountLock.processAccountWithLock(ProcessorBase.java:219)
	at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:208)
	at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:192)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-06-17 11:30:30,176 [http-bio-8080-exec-3] INFO  c.s.j.a.c.filter.LoggingFilter - 51 * Server out-bound response
51 < 400
51 < Content-Type: application/json
51 < 

2015-06-17 11:30:30,706 [http-bio-8080-exec-1] INFO  c.s.j.a.c.filter.LoggingFilter - 52 * Server in-bound request
52 > GET http://130.211.148.11:8080/1.0/kb/catalog/availableBasePlans
52 > host: 130.211.148.11:8080
52 > x-killbill-apikey: bob
52 > accept: application/json
52 > x-killbill-apisecret: lazar
52 > x-killbill-createdby: 
52 > content-type: application/json
52 > authorization: Basic YWRtaW46cGFzc3dvcmQ=
52 > connection: keep-alive
52 > user-agent: NING/1.0
52 > 

2015-06-17 11:30:30,707 [http-bio-8080-exec-1] INFO  c.s.j.a.c.filter.LoggingFilter - 52 * Server out-bound response
52 < 200
52 < Content-Type: application/json
52 < 

2015-06-17 11:30:30,913 [http-bio-8080-exec-2] INFO  c.s.j.a.c.filter.LoggingFilter - 53 * Server in-bound request
53 > GET http://130.211.148.11:8080/1.0/kb/accounts/7df5b5fd-8d1f-412d-83ff-ca9db3181d10/bundles
53 > host: 130.211.148.11:8080
53 > x-killbill-apikey: bob
53 > accept: application/json
53 > x-killbill-apisecret: lazar
53 > x-killbill-createdby: 1
53 > content-type: application/json
53 > authorization: Basic YWRtaW46cGFzc3dvcmQ=
53 > connection: keep-alive
53 > user-agent: NING/1.0
53 >

**Comment by pierre** [comment]
How is the setup different on the staging server? Do you maybe have a bad `stripe.yml` file deployed in `/var/tmp/bundles/plugins/ruby/killbill-stripe`?

**Comment by rachelswitzer** [comment]
I am having the exact same issues, but on local dev box. My stripe.yml file looks like this.

:stripe:
  :api_secret_key: 'my_key_here'
  :test: true

What did I do wrong?

**Comment by rachelswitzer** [comment]
It did not keep my indentions. But, I basically copied what was on the tutorial that he did.

**Comment by pierre** [comment]
@rachelswitzer Could you follow the configuration step (curl command) in the [README](https://github.com/killbill/killbill-stripe-plugin/blob/master/README.md) and remove your `stripe.yml` file to see if that helps?

**Comment by husam-otri** [comment]
Hey,

I followed the configuration step (curl command) and removed stripe.yml file; but i have got the same error!, @pierre  could you link me to the correct place to put some logs? might be i can provide more accurate logs

**Comment by pierre** [comment]
Could you create a [gist](https://gist.github.com/)? We'd also need the content of the `tenants` and `tenant_kvs` tables.

**Comment by rachelswitzer** [comment]
I completely started over. I delete everything and started again with KPM. I did not use the stripe.yml this time, just the curl command. The configuration curl command worked and I see the entry in my database but when I tried this 
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{
       "pluginName": "killbill-stripe",
       "pluginInfo": {
         "properties": [
           {
             "key": "token",
             "value": "t3GER3BP3JHLASZe"
           }
         ]
       }
     }' \
     "http://127.0.0.1:8080/1.0/kb/accounts/268983f2-5443-47e4-a967-b8962fc699c5/paymentMethods?isDefault=true"

it still failed with the same message
{"className":"org.killbill.billing.payment.api.PaymentApiException","code":7005,"message":"Failed to add payment method for account cf7646af-bacb-4b1f-8eea-8193776e11e7 : undefined method `[]' for nil:NilClass","causeClassName":null,"causeMessage":null,"stackTrace":[]}%      


I'll create gist with the contents of my tenants and tenant_kvs table. I do see the the values saved in the database.

Any assistance is greatly appreciated.

**Comment by pierre** [comment]
@rachelswitzer: just to confirm, is the configuration properly indented? I see something like that in your table:

```
:stripe:
:api_secret_key: "sk_test_XXXXXXXX"
:api_publishable_key: "pk_test_XXXXXXXXX"
```

instead of

```
:stripe:
  :api_secret_key: "sk_test_XXXXXXXX"
  :api_publishable_key: "pk_test_XXXXXXXXX"
```

**Comment by rachelswitzer** [comment]
That fixed it. The database was not storing the line breaks or the proper indention. I manually modified it and everything is working great now. I saw my transaction in stripe now.

Thanks again for all of your help.

**Comment by husam-otri** [comment]
I reinstalled everything again - actually i created stripe.yml manually - and its working now.

Thanks @pierre  for your help

**Comment by rachelswitzer** [comment]
I'm still having the issue of the yml file not being properly indented in the database. I've been working around this by modifying the entry. This has worked fine while I am in test and developing... but this won't work long term or in production. Any clue why this is happening still? I am using KillBill 14.0.

**Comment by RinkalTomar** [comment]
please help me 
how to add payment method on killBill kaui
I have followed step:
1.) Firstly I installed paypal getway.
2.) add payment pluging tab and fill input box (name ,password, signature) this 3 information i feeled 
but when i add payment method in my account then i got error.
ex:
Error while creating payment method: Error 400: Failed to add payment method for account 28a1d07d-a328-4b07-8c0c-c164b8967ed7 : Unable to lookup gateway for payment_processor_account_id default, kb_tenant_id = 070fed91-a50a-4e66-a39d-cde3d7081017, gateways: {}

please tell me how to set payment Method on my account
